### ISSUE TITLE
Errors on Linux MIPS LE

### ISSUE THREAD

**Issue by GitUser200607** [cbuijs/routedns-binaries#3]
`uname -m`
`mips`

`cat /proc/cpuinfo`
```
system type             : Broadcom BCM5300 chip rev 1 pkg 0
processor               : 0
cpu model               : MIPS 74K V4.9
BogoMIPS                : 299.82
wait instruction        : no
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : no
hardware watchpoint     : yes
ASEs implemented        : mips16 dsp
shadow register sets    : 1
VCED exceptions         : not available
VCEI exceptions         : not available

unaligned_instructions  : 1793254
dcache hits             : 2147483648
dcache misses           : 0
icache hits             : 2147483648
icache misses           : 0
instructions            : 2147483648
```
Running with help switch cause a lot of errors:
`./routedns --help`
```
runtime: epollcreate failed with 89
fatal error: runtime: netpollinit failed

goroutine 1 [running, locked to thread]:
runtime.throw({0x9893f2, 0x1b})
        /opt/routedns-binaries/go/src/runtime/panic.go:1047 +0x54 fp=0x10493f4 sp=0x10493e0 pc=0x5865c
runtime.netpollinit()
        /opt/routedns-binaries/go/src/runtime/netpoll_epoll.go:28 +0x290 fp=0x1049444 sp=0x10493f4 pc=0x52f84
runtime.netpollGenericInit()
        /opt/routedns-binaries/go/src/runtime/netpoll.go:197 +0x88 fp=0x104944c sp=0x1049444 pc=0x5204c
internal/poll.runtime_pollServerInit()
        /opt/routedns-binaries/go/src/runtime/netpoll.go:189 +0x38 fp=0x1049450 sp=0x104944c pc=0x95f1c
sync.(*Once).doSlow(0xecf3c8, 0x9b82bc)
        /opt/routedns-binaries/go/src/sync/once.go:74 +0x114 fp=0x1049478 sp=0x1049450 pc=0xa8504
sync.(*Once).Do(...)
        /opt/routedns-binaries/go/src/sync/once.go:65
internal/poll.(*pollDesc).init(0x1050214, 0x1050200)
        /opt/routedns-binaries/go/src/internal/poll/fd_poll_runtime.go:39 +0x6c fp=0x1049488 sp=0x1049478 pc=0x113e58
internal/poll.(*FD).Init(0x1050200, {0x97a028, 0x4}, 0x1)
        /opt/routedns-binaries/go/src/internal/poll/fd_unix.go:63 +0xc0 fp=0x104949c sp=0x1049488 pc=0x115078
os.newFile(0x3, {0x97f99f, 0xf}, 0x1)
        /opt/routedns-binaries/go/src/os/file_unix.go:209 +0x208 fp=0x10494c0 sp=0x104949c pc=0x123788
os.openFileNolog({0x97f99f, 0xf}, 0x0, 0x0)
        /opt/routedns-binaries/go/src/os/file_unix.go:274 +0x214 fp=0x10494ec sp=0x10494c0 pc=0x123a58
os.OpenFile({0x97f99f, 0xf}, 0x0, 0x0)
        /opt/routedns-binaries/go/src/os/file.go:326 +0x70 fp=0x104950c sp=0x10494ec pc=0x1217ec
os.Open(...)
        /opt/routedns-binaries/go/src/os/file.go:306
os.ReadFile({0x97f99f, 0xf})
        /opt/routedns-binaries/go/src/os/file.go:675 +0x70 fp=0x1049564 sp=0x104950c pc=0x121bb0
io/ioutil.ReadFile(...)
        /opt/routedns-binaries/go/src/io/ioutil/ioutil.go:37
golang.org/x/sys/cpu.readHWCAP()
        /tmp/routedns-build/go/pkg/mod/golang.org/x/sys@v0.10.0/cpu/hwcap_linux.go:42 +0x90 fp=0x1049594 sp=0x1049564 pc=0x40d278
golang.org/x/sys/cpu.archInit(...)
        /tmp/routedns-build/go/pkg/mod/golang.org/x/sys@v0.10.0/cpu/cpu_linux.go:11
golang.org/x/sys/cpu.init.0()
        /tmp/routedns-build/go/pkg/mod/golang.org/x/sys@v0.10.0/cpu/cpu.go:199 +0x3c fp=0x10495a0 sp=0x1049594 pc=0x40c9a8
runtime.doInit(0xe738e0)
        /opt/routedns-binaries/go/src/runtime/proc.go:6507 +0x1a8 fp=0x10496c0 sp=0x10495a0 pc=0x6e678
runtime.doInit(0xe78200)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x10497e0 sp=0x10496c0 pc=0x6e568
runtime.doInit(0xe72f20)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049900 sp=0x10497e0 pc=0x6e568
runtime.doInit(0xe729b0)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049a20 sp=0x1049900 pc=0x6e568
runtime.doInit(0xe76c20)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049b40 sp=0x1049a20 pc=0x6e568
runtime.doInit(0xe74520)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049c60 sp=0x1049b40 pc=0x6e568
runtime.doInit(0xe77a00)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049d80 sp=0x1049c60 pc=0x6e568
runtime.doInit(0xe77960)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049ea0 sp=0x1049d80 pc=0x6e568
runtime.doInit(0xe76b00)
        /opt/routedns-binaries/go/src/runtime/proc.go:6484 +0x98 fp=0x1049fc0 sp=0x1049ea0 pc=0x6e568
runtime.main()
        /opt/routedns-binaries/go/src/runtime/proc.go:233 +0x250 fp=0x1049fec sp=0x1049fc0 pc=0x5c4fc
runtime.goexit()
        /opt/routedns-binaries/go/src/runtime/asm_mipsx.s:617 +0x4 fp=0x1049fec sp=0x1049fec pc=0x9c16c

goroutine 2 [force gc (idle)]:
runtime.gopark(0x9b8640, 0xebd1d8, 0x11, 0x14, 0x1)
        /opt/routedns-binaries/go/src/runtime/proc.go:381 +0x124 fp=0x1038fd8 sp=0x1038fcc pc=0x5cb14
runtime.goparkunlock(...)
        /opt/routedns-binaries/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /opt/routedns-binaries/go/src/runtime/proc.go:305 +0x120 fp=0x1038fec sp=0x1038fd8 pc=0x5c8f4
runtime.goexit()
        /opt/routedns-binaries/go/src/runtime/asm_mipsx.s:617 +0x4 fp=0x1038fec sp=0x1038fec pc=0x9c16c
created by runtime.init.5
        /opt/routedns-binaries/go/src/runtime/proc.go:293 +0x44

goroutine 3 [GC sweep wait]:
runtime.gopark(0x9b8640, 0xebda30, 0xc, 0x14, 0x1)
        /opt/routedns-binaries/go/src/runtime/proc.go:381 +0x124 fp=0x10397c8 sp=0x10397bc pc=0x5cb14
runtime.goparkunlock(...)
        /opt/routedns-binaries/go/src/runtime/proc.go:387
runtime.bgsweep(0x104e000)
        /opt/routedns-binaries/go/src/runtime/mgcsweep.go:278 +0xdc fp=0x10397e4 sp=0x10397c8 pc=0x401ec
runtime.gcenable.func1()
        /opt/routedns-binaries/go/src/runtime/mgc.go:178 +0x64 fp=0x10397ec sp=0x10397e4 pc=0x2ddec
runtime.goexit()
        /opt/routedns-binaries/go/src/runtime/asm_mipsx.s:617 +0x4 fp=0x10397ec sp=0x10397ec pc=0x9c16c
created by runtime.gcenable
        /opt/routedns-binaries/go/src/runtime/mgc.go:178 +0xb4

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x9b8640, 0xebdd40, 0xd, 0x14, 0x2)
        /opt/routedns-binaries/go/src/runtime/proc.go:381 +0x124 fp=0x1039fbc sp=0x1039fb0 pc=0x5cb14
runtime.goparkunlock(...)
        /opt/routedns-binaries/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xebdd40)
        /opt/routedns-binaries/go/src/runtime/mgcscavenge.go:400 +0x94 fp=0x1039fd0 sp=0x1039fbc pc=0x3cd24
runtime.bgscavenge(0x104e000)
        /opt/routedns-binaries/go/src/runtime/mgcscavenge.go:628 +0x74 fp=0x1039fe4 sp=0x1039fd0 pc=0x3d724
runtime.gcenable.func2()
        /opt/routedns-binaries/go/src/runtime/mgc.go:179 +0x64 fp=0x1039fec sp=0x1039fe4 pc=0x2dd78
runtime.goexit()
        /opt/routedns-binaries/go/src/runtime/asm_mipsx.s:617 +0x4 fp=0x1039fec sp=0x1039fec pc=0x9c16c
created by runtime.gcenable
        /opt/routedns-binaries/go/src/runtime/mgc.go:179 +0x114

goroutine 5 [runnable]:
runtime.runfinq()
        /opt/routedns-binaries/go/src/runtime/mfinal.go:176 fp=0x10387ec sp=0x10387ec pc=0x2c888
runtime.goexit()
        /opt/routedns-binaries/go/src/runtime/asm_mipsx.s:617 +0x4 fp=0x10387ec sp=0x10387ec pc=0x9c16c
created by runtime.createfing
        /opt/routedns-binaries/go/src/runtime/mfinal.go:163 +0x98
```

Maybe there are missing dependencies for MIPS LE binaries?

**Comment by cbuijs** [comment]
Sorry for the extreme late response....

Seems that epoll is not supported on your OS. It is a common issue with Go on older environments. The kernel is too old.

**Comment by GitUser200607** [comment]
I am afraid, I have to close this issue. I don't use that router anymore. So can't answer.
